# Generated by Django 5.0.6 on 2024-05-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('itemName', models.CharField(max_length=200)),
                ('qty', models.CharField(max_length=10)),
            ],
        ),
    ]
